const stop_words = [
    "i",
    "me",
    "my",
    "myself",
    "we",
    "our",
    "ours",
    "ourselves",
    "you",
    "your",
    "yours",
    "yourself",
    "yourselves",
    "he",
    "him",
    "his",
    "himself",
    "she",
    "her",
    "hers",
    "herself",
    "it",
    "its",
    "itself",
    "they",
    "them",
    "their",
    "theirs",
    "themselves",
    "what",
    "which",
    "who",
    "whom",
    "this",
    "that",
    "these",
    "those",
    "am",
    "is",
    "are",
    "was",
    "were",
    "be",
    "been",
    "being",
    "have",
    "has",
    "had",
    "having",
    "do",
    "does",
    "did",
    "doing",
    "a",
    "an",
    "the",
    "and",
    "but",
    "if",
    "or",
    "because",
    "as",
    "until",
    "while",
    "of",
    "at",
    "by",
    "for",
    "with",
    "about",
    "against",
    "between",
    "into",
    "through",
    "during",
    "before",
    "after",
    "above",
    "below",
    "to",
    "from",
    "up",
    "down",
    "in",
    "out",
    "on",
    "off",
    "over",
    "under",
    "again",
    "further",
    "then",
    "once",
    "here",
    "there",
    "when",
    "where",
    "why",
    "how",
    "all",
    "any",
    "both",
    "each",
    "few",
    "more",
    "most",
    "other",
    "some",
    "such",
    "no",
    "nor",
    "not",
    "only",
    "own",
    "same",
    "so",
    "than",
    "too",
    "very",
    "s",
    "t",
    "can",
    "will",
    "just",
    "don",
    "should",
    "now"
]

const rawFeelingsWheel: any = {
    "happy": ["playful", "content", "interested", "proud", "accepted", "powerful", "peaceful", "trusting", "optimistic"],
    "playful": ["aroused", "cheeky"],
    "content": ["free", "joyful"],
    "interested": ["curious", "inquisitive"],
    "proud": ["successful", "confident"],
    "accepted": ["respected", "valued"],
    "powerful": ["courageous", "creative"],
    "peaceful": ["loving", "thankful"],
    "trusting": ["sensitive", "intimate"],
    "optimistic": ["hopeful", "inspired"],

    "sad": ["lonely", "vulnerable", "despair", "guilty", "depressed", "hurt"],
    "lonely": ["isolated", "abandoned"],
    "vulnerable": ["victimized", "fragile"],
    "despair": ["grief", "powerless"],
    "guilty": ["ashamed", "remorseful"],
    "depressed": ["inferior", "empty"],
    "hurt": ["embarrassed", "disappointed"],

    "disgusted": ["disapproving", "disappointed", "awful", "repelled"],
    "disapproving": ["judgmental", "embarrassed"],
    "disappointed": ["appalled", "revolted"],
    "awful": ["nauseated", "detestable"],
    "repelled": ["horrified", "hesitant"],

    "angry": ["let down", "humiliated", "bitter", "mad", "aggressive", "frustrated", "distant", "critical"],
    "let down": ["betrayed", "resentful"],
    "humiliated": ["disrespected", "ridiculed"],
    "bitter": ["indignant", "violated"],
    "mad": ["furious", "jealous"],
    "aggressive": ["provoked", "hostile"],
    "frustrated": ["infuriated", "annoyed"],
    "distant": ["withdrawn", "numb"],
    "critical": ["skeptical", "dismissive"],

    "fearful": ["scared", "anxious", "insecure", "weak", "rejected", "threatened"],
    "scared": ["helpless", "frightened"],
    "anxious": ["overwhelmed", "worried"],
    "insecure": ["inadequate", "inferior"],
    "weak": ["worthless", "insignificant"],
    "rejected": ["excluded", "persecuted"],
    "threatened": ["nervous", "exposed"],

    "bad": ["bored", "busy", "stressed", "tired"],
    "bored": ["indifferent", "apathetic"],
    "busy": ["pressured", "rushed"],
    "stressed": ["overwhelmed", "out of control"],
    "tired": ["sleepy", "unfocused"],

    "surprised": ["startled", "confused", "amazed", "excited"],
    "startled": ["shocked", "dismayed"],
    "confused": ["disillusioned", "perplexed"],
    "amazed": ["astonished", "awe"],
    "excited": ["eager", "energetic"]
}

let baseEmotions = [
    { emotion: "happy", background: "#FFC940", textColor: "#10161A"},
    { emotion: "sad", background: "#48AFF0", textColor: "#10161A"},
    { emotion: "disgusted", background: "#394B59", textColor: "#FFFFFF"},
    { emotion: "angry", background: "#FF7373", textColor: "#10161A"},
    { emotion: "fearful", background: "#FFB366", textColor: "#10161A"},
    { emotion: "bad", background: "#3DCC91", textColor: "#10161A"},
    { emotion: "surprised", background: "#C274C2", textColor: "#10161A"},
]
const base_emotions = [...baseEmotions];
let feelingsWheel: any = {};

while (baseEmotions.length > 0) {
    let emotion = baseEmotions.pop();
    if (typeof emotion === "undefined") break;
    if (typeof rawFeelingsWheel[emotion.emotion] === "undefined") continue;
    feelingsWheel[emotion.emotion] = rawFeelingsWheel[emotion.emotion].map((name: string) => {
        let processedEmotion = {
            emotion: name,
            background: emotion!.background,
            textColor: emotion!.textColor,
        }
        baseEmotions.push(processedEmotion)
        return processedEmotion;
    })
}



const emotions = [
    "enjoyment",
    "happiness",
    "love",
    "relief",
    "contentment",
    "amusement",
    "joy",
    "pride",
    "excitement",
    "peace",
    "satisfaction",
    "compassion",
    "sadness",
    "lonely",
    "heartbroken",
    "gloomy",
    "disappointed",
    "hopeless",
    "grieved",
    "unhappy",
    "lost",
    "troubled",
    "resigned",
    "miserable",
    "fear",
    "worried",
    "doubtful",
    "nervous",
    "anxious",
    "terrified",
    "panicked",
    // "horrified",
    "desperate",
    "confused",
    "stressed",
    "anger",
    "annoyed",
    "frustrated",
    "peeved",
    "contrary",
    "bitter",
    "infuriated",
    "irritated",
    "mad",
    "cheated",
    "vengeful",
    "insulted",
    "disgust",
    "dislike",
    "revulsion",
    "loathing",
    "disapproving",
    "offended",
    "horrified",
    "uncomfortable",
    "nauseated",
    "disturbed",
    "withdrawal",
    "aversion"
].concat([
    "resentful",
    "proud",
    "excited",
    "belittled",
    "intrigued",
    "curious",
    "wonder",
    "inspired",
    "tired",
    "exhausted",
    "bored"
])

export { 
    emotions as emotions,
    stop_words as stop_words,
    feelingsWheel as feelings_wheel,
    base_emotions as base_emotions,
};